services:
  web:  # Сервис для FastAPI
    build: .  # Строим образ из текущей директории
    ports:
      - "8000:8000"  # Пробрасываем порт 8000
    environment:
      DATABASE_URL: ${DATABASE_URL}  # URL для подключения к базе данных
    volumes:
      - ./src:/app
    depends_on:
      - db  # Указывает, что этот сервис зависит от db

  db:  # Сервис для PostgreSQL
    image: postgres:16.4-alpine  # Используем образ PostgreSQL
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Используем переменную окружения
      POSTGRES_USER: ${POSTGRES_USER}  # Используем переменную окружения
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Используем переменную окружения
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Храним данные базы данных в томе

volumes:
  db_data:  # Определяем том для хранения данных
