services:
  web:  # Сервис для FastAPI
    build: .  # Строим образ из текущей директории
    ports:
      - "8000:8000"  # Пробрасываем порт 8000
    environment:
      DATABASE_URL: postgresql://postgres:B10vvyMz@db:5432/postgres  # URL для подключения к базе данных
    volumes:
      - ./src:/app
    depends_on:
      - db  # Указывает, что этот сервис зависит от db

  db:  # Сервис для PostgreSQL
    image: postgres:16.4-alpine  # Используем образ PostgreSQL
    environment:
      POSTGRES_DB: postgres  # Имя базы данных
      POSTGRES_USER: postgres  # Имя пользователя
      POSTGRES_PASSWORD: B10vvyMz  # Пароль
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Храним данные базы данных в томе

volumes:
  db_data:  # Определяем том для хранения данных
