"""Добавлен Уникальный составной индекс для order_id и product_id

Revision ID: 85afd4a2335c
Revises: ae1ab1e4fc9f
Create Date: 2025-03-24 15:37:38.621372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85afd4a2335c'
down_revision: Union[str, None] = 'ae1ab1e4fc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_order_product', 'order_items', ['order_id', 'product_id'])
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.alter_column('orders', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint('uq_order_product', 'order_items', type_='unique')
    # ### end Alembic commands ###
