"""Изменение параметров значений

Revision ID: ae1ab1e4fc9f
Revises: 41b33f00bf9d
Create Date: 2025-03-21 13:52:49.724771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1ab1e4fc9f'
down_revision: Union[str, None] = '41b33f00bf9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'order_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order_items', 'order_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
